# ===== common (local/prod 공통) =====
spring:
  application:
    name: NICHIYA
    version: ${version:unknown}
  profiles:
    active: prod

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: kr.co.bnk_marketproject_be.dto

  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  servlet:
    context-path: /NICHIYA

# ===== local =====
---
spring:
  config:
    activate.on-profile: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: NICHIYA
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update            # 로컬 개발은 편하게 update
    open-in-view: false
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.mybatis: info

# ===== prod (운영) =====
---
spring:
  config:
    activate.on-profile: prod
  datasource:
    url: jdbc:oracle:thin:@//43.200.69.114:1522/XEPDB1   # Service name 방식
    username: NICHIYA
    password: 1234         # 환경변수로 주입
  jpa:
    hibernate:
      ddl-auto: none              # ★ 스키마 올리기 전엔 none
    open-in-view: false
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your@gmail.com
    password: your-google-app-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8

# 어드민 로고 업로드 경로 (배포용 세현 수정)
app:
  upload:
    dir: /var/nichiya/uploads
  base-url: http://localhost:8080/NICHIYA  #테스트용
  #base-url: http://43.200.69.114:8080/NICHIYA